#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Mod from P3TERX
#=================================================

name: OpenWrt

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      SSH_ACTIONS:
        description: 'Needs to create a ssh debug session?'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
    build:
      runs-on: ubuntu-18.04
      if: github.event.repository.owner.id == github.event.sender.id

      steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Username
        id: set_name
        run: |
          if [ "$GITHUB_ACTOR" = "gyj1109" ];then
            echo "##[set-output name=username;]Gyj1109"
          else
            echo "##[set-output name=username;]`echo $GITHUB_REPOSITORY | cut -d / -f 2`"
          fi

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
          sudo -E apt-get update -y
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y antlr3 asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache coreutils curl device-tree-compiler ecj fastjar flex g++-8-multilib gawk gcc-8 gcc-8-multilib gcc++-8 gettext git git-core gperf haveged intltool jq lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libreadline-dev libssl-dev libtool libz-dev lrzsz msmtp nano p7zip p7zip-full patch python python-pip python-ply python3 python3-pip python3-ply qemu-utils re2c rsync scons subversion tar texinfo uglifyjs unzip upx vim wget xmlto xz-utils zlib1g-dev
          for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done
          sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
          sudo -E apt-get autoremove -y --purge
          sudo -E apt-get clean -y
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"

      - name: Clone Source
        run: |
          git clone -b openwrt-18.06-k5.4 --single-branch https://github.com/project-openwrt/openwrt openwrt
          sudo chown -R runner:runner openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config
        run: |
          cd openwrt
          mv ../.config .config

      - name: Additional Step
        run: |
          bash addon_steps.sh

      - name: Set Build Time
        id: set_time
        run: |
          build_time=$(date +%Y-%m-%dT%H-%M)
          echo -e "\033[32m\033[1m$build_time\033[0m"
          echo "##[set-output name=build_time;]$build_time"

      - name: Setup Debug Session
        if: github.event.inputs.SSH_ACTIONS == 'true'
        uses: tete1030/safe-debugger-action@dev

      - name: Make
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cd openwrt
          make defconfig
          make -j$[$(nproc)+1]

      - name: Rebuild to Collect Error Log
        if: failure()
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cd openwrt
          make -j1 V=s

      - name: Organize Files
        run: |
          cd openwrt
          cp .config ../artifact/config.seed
          ./scripts/diffconfig.sh > ../artifact/config.slim.seed
          cd ../artifact/
          rm ../openwrt/bin/targets/x86/64/*rootfs*.img
          mv -f ../openwrt/bin/targets/x86/64/*.img .
          echo -e "MD5:    \c" > checksums
          md5sum *.img | grep squashfs | cut -d " " -f 1 >> checksums
          echo -e "SHA256: \c" >> checksums
          sha256sum *.img | grep squashfs | cut -d " " -f 1 >> checksums
          gzip *.img
          cp checksums ../body.md
          zip ../OpenWrt-${{ steps.set_name.outputs.username }}-${{ steps.set_time.outputs.build_time }}-ROM.zip *
          cd ..
          sed -i 's/:\ \+/:\t/g' body.md
          sed -i '1iBuilt at ${{ steps.set_time.outputs.build_time }}' body.md
          cd openwrt/bin/targets/x86/64/packages
          zip ../../../../../../OpenWrt-${{ steps.set_name.outputs.username }}-${{ steps.set_time.outputs.build_time }}-Packages.zip *

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt-${{ steps.set_name.outputs.username }}-${{ steps.set_time.outputs.build_time }}-ROM
          path: ./artifact/

      - name: Upload Packages
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt-${{ steps.set_name.outputs.username }}-${{ steps.set_time.outputs.build_time }}-Packages
          path: ./openwrt/bin/targets/x86/64/packages

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "OpenWrt-${{ steps.set_name.outputs.username }}-*.zip,artifact/config.seed"
          bodyFile: "body.md"
          commit: ${{ github.sha }}
          name: OpenWrt-${{ steps.set_name.outputs.username }}-${{ steps.set_time.outputs.build_time }}
          tag: ${{ steps.set_time.outputs.build_time }}
          token: ${{ secrets.sec_token }}
